version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 'FI:NG:ER:PR:INT' # deploy key added to dependency repo
      - run: ssh-add -L # This shows that the key was successfully added
      - run: npm ci # or `npm install` The failure is here
      - run: npm test