jobs:
  build:
    docker:
      - image: 'circleci/node:10'
    steps:
      - checkout
      - run: echo your BUILD code here
version: 2.1
workflows:
  build_and_test:
    jobs:
      - build
      - loadtest/loadtest:
          nWorkers: 2
          requires:
            - build
          susTime: 30
          targetHostUrl: 'https://www.10travlr.com.au'
  version: 2