cypress-e2e-chrome:
  image: cypress/browsers:chrome62
  stage: test
  script:    
    - chrome --version
    - npm install --save-dev cypress
    - $(npm bin)/cypress run  --record --key a-beautiful-key --browser chrome
  artifacts:
    expire_in: 1 week
    paths:
    - cypress/screenshots
    - cypress/videos
