version: 2.1
orbs:
  node: 'circleci/node:4.1'
  slack: circleci/slack@4.1
jobs:
  build:
    docker:
      - image: cypress/included:4.10.0
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          # cache NPM modules and the folder with the Cypress binary
          paths:
            - ~/.npm
            - ~/.cache
      - run:  npm run 10travlr-production

  deploy:
    executor:
      name: node/default

    steps:
      - slack/notify:
          channel: 'G01HCGG1C4E'
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*This is a text notification*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always

      

workflows:
  test-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build