version: 2.1

jobs:
  k6_local_test:
    docker:
      - image: "cimg/base:stable"
    runs-on:
      - ubuntu-latest
    container: 
      - docker://loadimpact/k6:latest
    steps: 
      - checkout
      - run: k6 run docker/script.js
