version: 2.1

jobs:
  build:
    docker:
      - image: cypress/included:4.10.0
    environment:
        TERM: xterm
    working_directory: ~/app

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: npm ci

      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      
      - persist_to_workspace:
          root: ~/
          paths:
            - app
            - .cache/Cypress

  default: &defaults
  parallelism: 1
  working_directory: ~/my-project

  k6_performance_tests: &k6_performance_tests
    run:
      name: Running k6 tests
      command: |
        # Download the k6 docker image. Alternatively, download the k6 release binary
        docker pull loadimpact/k6:latest
        # Mount a volume to access the folder and run the test
        npm run k6-performance-test

  run_performance_tests:
    machine: true
    steps:
      - checkout
      - *k6_performance_tests

workflows:

  build-and-test:
    jobs:
      - build
      - run_performance_tests