version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    working_directory: ~/project

    steps:
      - checkout
      - run: brew install k6
      - run: k6 run basic/script.js
