version: 2.1
orbs:
      slack: circleci/slack@4.1
jobs:
  build-regression-test:
    docker:
      - image: cypress/included:4.10.0
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          # cache NPM modules and the folder with the Cypress binary
          paths:
            - ~/.npm
            - ~/.cache
      - run: npm run 10travlr-production

  build-slack-notification:
    deploy:
      docker:
        - image: 'cimg/base:stable'

      steps:
        - run: echo "deploy my app"
        - slack/notify:
          event: fail
          mentions: '@EngineeringTeam'
          template: basic_fail_1
        - slack/notify:
          event: pass
          template: success_tagged_deploy_1

    test:
      docker:
        - image: 'cimg/base:stable'

      steps:
        - run: echo "test my app"
    

workflows:
  version: 2
  build_deploy_and_notify: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - test
      - slack/on-hold:
          context: slack-secrets
          filters:
            tags:
              only: /^v.*/
          requires:
            - test
      - pause_workflow:
          filters:
            tags:
              only: /^v.*/
          requires:
            - test
            - slack/on-hold
          type: approval
      - deploy:
          filters:
            tags:
              only: /^v.*/
          requires:
            - pause_workflow


          
  
