version: '2.1'
orbs:
  slack: circleci/slack@4.1
jobs:
  deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - run: npm run deploy
      - slack/notify:
          channel: C01HK2BGK1T
          mentions: '@here'
          event: fail
          template: basic_fail_1
      - slack/notify:
          channel: C01HK2BGK1T
          event: pass
          template: success_tagged_deploy_1
  test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - run: npm run deploys

workflows:
  test-and-deploy:
    jobs:
      - test
      - slack/on-hold:
          context: test-context
          filters:
            tags:
              only: /^v.*/
          requires:
            - test
      - pause_workflow:
          filters:
            tags:
              only: /^v.*/
          requires:
            - test
            - slack/on-hold
          type: approval
      - deploy:
          filters:
            tags:
              only: /^v.*/
          requires:
            - pause_workflow
