version: 2.1
  
  
jobs:

  build:
    docker:
      - image: cypress/included:4.10.0
    environment:
      TERM: xterm
    working_directory: ~/app

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: npm ci
          
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      
      - persist_to_workspace:
          root: ~/
          paths:
            - app
            - .cache/Cypress

  regression-test:
    docker:
      - image: loadimpact/k6:latest
    environment:
        TERM: xterm
    working_directory: ~/app

    steps:
      - attach_workspace:
          at: ~/
      - run: 
        - npm run k6-performance-test

workflows:
  test-and-deploy:
    jobs:
      - build
      - regression-test:
          requires:
            - build
    
