version: 2.1
orbs:
  cypress: cypress-io/cypress@1.26.0
workflows:
  build:
    jobs:
      - cypress/run:
          docker:
            - image: cypress/included:4.10.0
          command: npm run 10travlr-production
