version: 2.1

jobs:

  build:
    docker:
      - image: cypress/included:4.10.0
        environment:
          TERM: xterm
      - image: loadimpact/k6:latest

    steps:
      - run: npm run k6-test
      