version: 2.1
orbs:
  cypress: cypress-io/cypress@1.26.0
  newman: postman/newman@0.0.2
  slack: circleci/slack@4.2.0
  node: circleci/node@4.1

  # k6 Performance Testing only run once a week in friday.

jobs:
  k6-performance-testing:
    machine: true

    steps:
    - checkout
    
    - run: 
        name: pull-loadimpact-docker
        command: docker pull loadimpact/k6:latest

    - run: 
        name: smoke-testing
        command: npm run k6-smoke-testing

    - run: 
        name: load-testing
        command: npm run k6-load-testing

    - run: 
        name: soak-testing
        command: npm run k6-soak-testing

    - run: 
        name: stress-testing
        command: npm run k6-stress-testing
    
  api-testing:
    executor: newman/postman-newman-docker

    steps:
      - checkout

      - run: 
          name: Postman
          command: npm run postman-api-test

  deploy:
    executor: 
      name: node/default

    steps:
      - checkout
      - node/install-packages
      
      - slack/notify:
          channel: C01HK2BGK1T
          mentions: '@here'
          event: fail
          template: basic_fail_1
      - slack/notify:
          channel: C01HK2BGK1T
          event: pass
          template: success_tagged_deploy_1
          
workflows: 
  build:
    jobs:
      - cypress/install

      - k6-performance-testing

      - api-testing

      - cypress/run:
          name: regression-testing
          requires:
            - "cypress/install"
          command: npm run 10travlr-production

      - pause_workflow:
          filters:
            tags:
              only: /^v.*/
          requires:
            - "regression-testing"
            # - "k6-performance-testing"
            - "api-testing"
          type: approval
      
      - deploy:
          context: test-context
          filters:
            tags:
              only: /^v.*/
          requires:
            - "pause_workflow"
          