version: 2
jobs:
  build-regression-test:
    docker:
    - image: cypress/included:4.10.0
      environment:
      ## this enables colors in the output
      TERM: xterm
      working_directory: ~/app
      steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          # cache NPM modules and the folder with the Cypress binary
          paths:
            - ~/.npm
            - ~/.cache
      - run: npm run 10travlr-production

  build-slack-notification:
    orbs:
      slack: circleci/slack@4.1.4
    docker:
      image: 'cimg/base:stable'
      steps:
        - slack/notify:
          channel: 'G01HKFZTB9R'
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*This is a text notification*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always

workflows:
  version: 2
  build_and_deploy: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - build-regression-test
      - build-slack-notification:
          context: test-context
          requires:
            - build-regression-test
          
  
