jobs:
  build:
    docker:
      - image: 'circleci/python:3.6'
    steps:
      - loadtest/loadtest:
          nWorkers: 2
          susTime: 30
          targetHostUrl: 'https://www.10travlr.com.au'
version: 2.1