version: '2.1'
orbs:
  node: circleci/node@4.1
  slack: circleci/slack@4.1
docker:
  - image: cypress/included:4.10.0
  environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app
jobs:
  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run 10travlr-production
      - slack/notify:
          event: fail
          mentions: '@EngineeringTeam'
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
workflows:
  deploy_and_notify:
    jobs:
      - deploy:
          context: test-context