version: 2.1

jobs:

  build:
    docker:
      - image: cypress/included:4.10.0
    
    run:
      name: pull-docker
      command: |
          docker pull loadimpact/k6:latest

    working_directory: ~/app

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: npm ci

      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      
      - persist_to_workspace:
          root: ~/
          paths:
            - app
            - .cache/Cypress
      
      - run:   npm run k6-tests