version: 2.1

jobs:

  build:
    docker:
      - image: cypress/browsers:node14.7.0-chrome84
    environment:
      TERM: xterm
  working_directory: ~/app

  steps:
      - checkout
      - restore_cache:
          key: cache-dirs-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "circle.yml" }}
      - run: npm ci

      # Use Git commit message to install any pre-release versions of Cypress
      - run: npm i -g @cypress/commit-message-install
      # if there is no special JSON comment in the current commit body
      # then this command does nothing
      - run: commit-message-install --else "echo nothing custom to install"

      # run verify and then save cache.
      # this ensures that the Cypress verified status is cached too
      - run: npm run cypress:verify
      - run: npm run cypress:info
      - run: npm run stop-only
      - save_cache:
          key: cache-dirs-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "circle.yml" }}
          paths:
            - ~/.npm
            - ~/.cache
      # all other test jobs will run AFTER this build job finishes
      # to avoid reinstalling dependencies, we persist the source folder "app"
      # and the Cypress binary to workspace, which is the fastest way
      # for Circle jobs to pass files
      - persist_to_workspace:
          root: ~/
          paths:
            - app
            - .cache/Cypress  

  regression-test:
    working_directory: ~/app
    docker:
      - image: cypress/browsers:node14.7.0-chrome84
    environment:
      TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run 10travlr-production

  deploy:
    docker:
      - image: 'cimg/base:stable'

    steps:
      - slack/notify:
          channel: C01HK2BGK1T
          mentions: '@here'
          event: fail
          template: basic_fail_1
      - slack/notify:
          channel: C01HK2BGK1T
          event: pass
          template: success_tagged_deploy_1

workflows:
  test-and-deploy:
    jobs:
      - build
      - regression-test
      - pause_workflow:
          filters:
            tags:
              only: /^v.*/
          requires:
            - regression-test
          type: approval
      - deploy:
          context: test-context
          filters:
            tags:
              only: /^v.*/
          requires:
            - pause_workflow
            #