version: 2.1
orbs:
  cypress: cypress-io/cypress@1.26.0
workflows:
  build:
    jobs:
      - cypress/install
      - cypress/run:
          name: regression-test
          requires:
            - "cypress/install"
          executor: cypress/base-10