version: 2.1
orbs:
  cypress: cypress-io/cypress@1.26.0
workflows:
  build:
    jobs:
      - cypress/run:
          executors: 'cypress/included:latest'
          command: npm run 10travlr-production
