version: 2.1
orbs:
  cypress: cypress-io/cypress@1.26.0
  newman: postman/newman@0.0.2
  slack: circleci/slack@4.2.0
  node: circleci/node@4.1

jobs: 
  api-testing:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - run: npm run api-test

  deploy:
    executor: 
      name: node/default

    steps:
      - checkout
      - node/install-packages
      
      - slack/notify:
          channel: C01HK2BGK1T
          mentions: '@here'
          event: fail
          template: basic_fail_1
      - slack/notify:
          channel: C01HK2BGK1T
          event: pass
          template: success_tagged_deploy_1


k6_performance_tests: &k6_performance_tests
    run:
    name: Running k6 tests
    # Download the k6 docker image. Alternatively, download the k6 release binary
    # Mount a volume to access the folder and run the test
    command: |
      docker pull loadimpact/k6:latest
      docker run -i loadimpact/k6 run - < /Users/reposado/Cypress.io/cypress/integration/10travlr/production/k6/script.js

run_performance_tests:
  machine: true
  steps:
    - checkout
    - *k6_performance_tests
          


workflows: 
  build:
    jobs:
      - cypress/install
      - run_performance_tests

      - cypress/run:
          name: regression-testing
          requires:
            - "cypress/install"
          command: npm run 10travlr-production
      
      - api-testing:
          requires:
            - "cypress/install"

      - pause_workflow:
          filters:
            tags:
              only: /^v.*/
          requires:
            - "regression-testing"
            - "api-testing"
          type: approval
      
      - deploy:
          context: test-context
          filters:
            tags:
              only: /^v.*/
          requires:
            - "pause_workflow"
          