version: 2.1
orbs:
  cypress: cypress-io/cypress@1.26.0
  node: circleci/node@4.1.0

jobs:

  build:
    docker:
      - image: loadimpact/k6:latest
    working_directory: ~/app

    steps:
      - checkout
      - run: npm run k6-tests