version: 2.1
orbs:
  cypress: cypress-io/cypress@1.26.0
workflows:
  build:
    jobs:
      - cypress/install:
          build: npm run build
      - cypress/run:
          name: regression-test
          requires:
            - "cypress/install"
          command: npm run 10travlr-production