version: 2.1

orbs:
  docker: circleci/docker@1.5.0

jobs:

  build: 
    docker: 
      - image: loadimpact/k6:latest
    environment:
      TERM: xterm
    working_directory: ~/app

    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run: 
          - docker pull loadimpact/k6:latest
          - docker run -i loadimpact/k6 run - < /Cypress.io/k6/script.js




workflow:
  test:
    jobs:
      - build