version: 2.1
orbs:
  cypress: cypress-io/cypress@1.26.0
  newman: postman/newman@0.0.2

jobs:
  api-testing:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - run: npm run api-test
workflows:
  build:
    jobs:
      - cypress/install

      - cypress/run:
          name: regression-test
          requires:
            - "cypress/install"
          command: npm run 10travlr-production
      
      - api-testing:
          requires:
            - "cypress/install"