version: 2.1

jobs:
  k6-build:
    docker:
      - pull loadimpact/k6:latest
      
  run_performance_tests:
    machine: true

    - attach_workspace:
          at: ~/
      - run: npm run k6-performance-test

workflows:
  version: 2
  build-and-test:
    jobs:
      - run_performance_tests