version: 2.1

jobs:

  build:
    docker:
      - image: cypress/included:4.10.0
        environment:
          TERM: xterm
          

    steps:
      - checkout
      - run: 
          name: Running k6 tests
          command: |
            docker pull loadimpact/k6:latest