version: 2.1
orbs:
  cypress: cypress-io/cypress@1.26.0
  newman: postman/newman@0.0.2
  slack: circleci/slack@4.2.0
  node: circleci/node@4.1

jobs: 
  api-testing:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - run: npm run api-test

  deploy:
    docker:
      - image: 'cimg/base:stable'
    
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run deploy
      - slack/notify:
          channel: C01HK2BGK1T
          mentions: '@here'
          event: fail
          template: basic_fail_1
      - slack/notify:
          channel: C01HK2BGK1T
          event: pass
          template: success_tagged_deploy_1





workflows: 
  build:
    jobs:
      - cypress/install

      - cypress/run:
          name: regression-testing
          requires:
            - "cypress/install"
          command: npm run 10travlr-production
      
      - api-testing:
          requires:
            - "cypress/install"

      - pause_workflow:
          filters:
            tags:
              only: /^v.*/
          requires:
            - "regression-testing"
            - "api-testing"
      
      - deploy:
          requires:
            - "regression-testing"