version: 2.1

orbs:
  slack: circleci/slack@4.1

jobs:

  build:
    docker:
      - image: cypress/included:4.10.0
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: npm ci

      - run: npm run cypress:verify

      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          # cache NPM modules and the folder with the Cypress binary
          paths:
            - ~/.npm
            - ~/.cache

  regression-test:
    docker:
      - image: cypress/browsers:node14.7.0-chrome84
    environment:
      TERM: xterm
    working_directory: ~/app

    steps:
      - attach_workspace:
          at: ~/
      - run: npm run 10travlr-production

  deploy:
    docker:
      - image: 'cimg/base:stable'

    steps:
      - slack/notify:
          channel: C01HK2BGK1T
          mentions: '@here'
          event: fail
          template: basic_fail_1
      - slack/notify:
          channel: C01HK2BGK1T
          event: pass
          template: success_tagged_deploy_1

workflows:
  test-and-deploy:
    jobs:
      - build
      - regression-test:
          requires: 
            - build
      - pause_workflow:
          filters:
            tags:
              only: /^v.*/
          requires:
            - regression-test
          type: approval
      - deploy:
          context: test-context
          filters:
            tags:
              only: /^v.*/
          requires:
            - pause_workflow
            #